version: '3.7'
services:
  api:
    build: 
      context: ./backend
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node/node_modules
      - .:/app
  scan:
    build:
      context: ./backend
      dockerfile: ./scan/Dockerfile
    volumes:
      - /home/node/node_modules
      - .:/app
  database:
    image: 'postgres:alpine'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=associate_engine
