version: '3.7'
services:
  api:
    build:
      context: ./backend
      dockerfile: ./api/Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./backend/package.json:/opt/app/package.json
      - ./backend/api:/opt/app/api
      - ./backend/prisma:/opt/app/prisma
  scan:
    build:
      context: ./backend
      dockerfile: ./scan/Dockerfile
    volumes:
      - ./backend/package.json:/opt/app/package.json
      - ./backend/scan:/opt/app/scan
      - ./backend/prisma:/opt/app/prisma
